name: cmip6-utils
channels:
  - conda-forge
  - defaults
dependencies:
  - netcdf4=1.6.0
  - charset-normalizer=2.1.0
  - cdsapi=0.5.1
  - cffi=1.15.1
  - numpy=1.23.1
  - libbrotlidec=1.0.9
  - libtool=2.4.6
  - libedit=3.1.20191231
  - matplotlib=3.5.2
  - jupyterlab=3.4.4
  - libcblas=3.9.0
  - soupsieve=2.3.2.post1
  - libcups=2.3.3
  - lcms2=2.12
  - asttokens=2.0.5
  - xcb-util=0.4.0
  - font-ttf-source-code-pro=2.038
  - websocket-client=1.3.3
  - tornado=6.2
  - libsndfile=1.0.31
  - notebook-shim=0.1.0
  - dbus=1.13.6
  - libzlib=1.2.12
  - libopenblas=0.3.20
  - libzip=1.9.2
  - ncurses=6.3
  - gettext=0.19.8.1
  - notebook=6.4.12
  - jsonschema=4.9.0
  - fftw=3.3.10
  - libxml2=2.9.14
  - pure_eval=0.2.2
  - libvorbis=1.3.7
  - jpeg=9e
  - libclang13=14.0.6
  - fonts-conda-forge=1
  - libcurl=7.83.1
  - liblapack=3.9.0
  - tk=8.6.12
  - curl=7.83.1
  - ipykernel=6.15.1
  - xz=5.2.5
  - jupyter_client=7.3.4
  - hdf4=4.2.15
  - jupyterlab_server=2.15.0
  - nbclassic=0.4.3
  - parso=0.8.3
  - pcre=8.45
  - backcall=0.2.0
  - toml=0.10.2
  - babel=2.10.3
  - libssh2=1.10.0
  - libbrotlicommon=1.0.9
  - nbformat=5.4.0
  - six=1.16.0
  - ld_impl_linux-64=2.36.1
  - traitlets=5.3.0
  - json5=0.9.5
  - libstdcxx-ng=12.1.0
  - gstreamer=1.20.3
  - libdb=6.2.32
  - sqlite=3.39.2
  - xorg-libxau=1.0.9
  - argon2-cffi-bindings=21.2.0
  - ply=3.11
  - pycparser=2.21
  - pygments=2.12.0
  - colorama=0.4.5
  - pip=22.2.1
  - libgfortran-ng=12.1.0
  - python=3.9.13
  - gst-plugins-base=1.20.3
  - krb5=1.19.3
  - munkres=1.1.4
  - libdeflate=1.12
  - defusedxml=0.7.1
  - configobj=5.0.6
  - xarray=2022.6.0
  - wcwidth=0.2.5
  - pandocfilters=1.5.0
  - matplotlib-base=3.5.2
  - readline=8.1.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - _openmp_mutex=4.5
  - xorg-libxdmcp=1.1.3
  - pexpect=4.8.0
  - anyio=3.6.1
  - nbconvert-pandoc=6.5.0
  - libgcc-ng=12.1.0
  - sip=6.6.2
  - libxkbcommon=1.0.3
  - libxcb=1.13
  - nbclient=0.6.6
  - beautifulsoup4=4.11.1
  - pytz=2022.1
  - zipp=3.8.0
  - c-ares=1.18.1
  - libffi=3.4.2
  - backports.functools_lru_cache=1.6.4
  - pyqt=5.15.7
  - libevent=2.1.10
  - ptyprocess=0.7.0
  - brotli-bin=1.0.9
  - libuuid=2.32.1
  - ipython=8.4.0
  - libwebp=1.2.3
  - pillow=9.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - importlib_metadata=4.11.4
  - libwebp-base=1.2.3
  - ipython_genutils=0.2.0
  - libflac=1.3.4
  - nbconvert=6.5.0
  - libbrotlienc=1.0.9
  - pickleshare=0.7.5
  - pyzmq=23.2.0
  - qt-main=5.15.4
  - debugpy=1.6.0
  - libsodium=1.0.18
  - psutil=5.9.1
  - jedi=0.18.1
  - pyjwt=2.6.0
  - wheel=0.37.1
  - importlib_resources=5.9.0
  - tinycss2=1.1.1
  - libgomp=12.1.0
  - alsa-lib=1.2.6.1
  - nbconvert-core=6.5.0
  - backports=1.0
  - prometheus_client=0.14.1
  - libcap=2.64
  - fontconfig=2.14.0
  - tqdm=4.64.0
  - pandas=1.4.3
  - jinja2=3.1.2
  - zlib=1.2.12
  - mysql-common=8.0.29
  - matplotlib-inline=0.1.3
  - zeromq=4.3.4
  - pulseaudio=14.0
  - flit-core=3.7.1
  - python-dateutil=2.8.2
  - pyopenssl=22.0.0
  - freetype=2.10.4
  - importlib-metadata=4.11.4
  - font-ttf-inconsolata=3.000
  - libiconv=1.16
  - packaging=21.3
  - libudev1=249
  - terminado=0.15.0
  - bleach=5.0.1
  - jupyter_server=1.18.1
  - attr=2.5.1
  - python-fastjsonschema=2.16.1
  - mysql-libs=8.0.29
  - glib-tools=2.72.1
  - pthread-stubs=0.4
  - hdf5=1.12.2
  - xcb-util-renderutil=0.3.9
  - font-ttf-ubuntu=0.83
  - libnetcdf=4.8.1
  - python_abi=3.9
  - libnghttp2=1.47.0
  - libpng=1.6.37
  - libtiff=4.4.0
  - icu=70.1
  - glib=2.72.1
  - pyparsing=3.0.9
  - argon2-cffi=21.3.0
  - brotli=1.0.9
  - certifi
  - keyutils=1.6.1
  - decorator=5.1.1
  - entrypoints=0.4
  - nest-asyncio=1.5.5
  - xcb-util-image=0.4.0
  - jupyterlab_pygments=0.2.2
  - libev=4.33
  - tzdata=2022a
  - fonts-conda-ecosystem=1
  - pyrsistent=0.18.1
  - executing=0.9.1
  - zstd=1.5.2
  - attrs=22.1.0
  - lerc=4.0.0
  - sniffio=1.2.0
  - setuptools=63.2.0
  - ca-certificates
  - pysocks=1.7.1
  - libogg=1.3.4
  - nspr=4.32
  - libgfortran5=12.1.0
  - libpq=14.4
  - unicodedata2=14.0.0
  - libllvm14=14.0.6
  - libglib=2.72.1
  - urllib3=1.26.11
  - xcb-util-keysyms=0.4.0
  - xcb-util-wm=0.4.1
  - jupyter_core=4.11.1
  - kiwisolver=1.4.4
  - markupsafe=2.1.1
  - webencodings=0.5.1
  - jack=1.9.18
  - lz4-c=1.9.3
  - portaudio=19.6.0
  - fonttools=4.34.4
  - pandoc=2.18
  - libopus=1.3.1
  - cftime=1.6.1
  - libclang=14.0.6
  - expat=2.4.8
  - pkgutil-resolve-name=1.3.10
  - libblas=3.9.0
  - giflib=5.2.1
  - openssl
  - idna=3.3
  - pyqt5-sip=12.11.0
  - cycler=0.11.0
  - prompt-toolkit=3.0.30
  - stack_data=0.3.0
  - libnsl=2.0.0
  - nss=3.78
  - requests=2.28.1
  - mistune=0.8.4
  - send2trash=1.8.0
  - openjpeg=2.4.0
  - _libgcc_mutex=0.1
  - globus-cli
  - pytest
  - xesmf
  - xclim
  - cartopy
  - nc-time-axis
  - hvplot
  - panel
  - black
  - jupyter_bokeh
